from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .caption_node import NODE_CLASS_MAPPINGS_CAPTION, NODE_DISPLAY_NAME_MAPPINGS_CAPTION
from .caption_options import NODE_CLASS_MAPPINGS_OPTIONS, NODE_DISPLAY_NAME_MAPPINGS_OPTIONS
from .batch_prompt_node import NODE_CLASS_MAPPINGS_BATCH_PROMPT, NODE_DISPLAY_NAME_MAPPINGS_BATCH_PROMPT

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS,
    **NODE_CLASS_MAPPINGS_CAPTION,
    **NODE_CLASS_MAPPINGS_OPTIONS,
    **NODE_CLASS_MAPPINGS_BATCH_PROMPT,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS,
    **NODE_DISPLAY_NAME_MAPPINGS_CAPTION,
    **NODE_DISPLAY_NAME_MAPPINGS_OPTIONS,
    **NODE_DISPLAY_NAME_MAPPINGS_BATCH_PROMPT,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
